version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: "${API_IMAGE}"

  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: "${CLIENT_IMAGE}"
    ports:
      - 3000
    depends_on:
      - api