"""added session_id

Revision ID: 7688edfdf4b8
Revises: 
Create Date: 2021-02-03 02:42:41.062054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7688edfdf4b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    op.drop_table('user')
    op.drop_table('response_time')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_time',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('problem_id', sa.INTEGER(), nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('contest_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('entry_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('response',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('response_str', sa.VARCHAR(length=150), nullable=False),
    sa.Column('contest_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('entry_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def upgrade_response():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('response_time', sa.Column('session_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_response():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_time', 'session_id')
    op.drop_column('response', 'session_id')
    # ### end Alembic commands ###

